name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run TypeScript compiler check
        run: bunx tsc --noEmit

      - name: Run unit tests
        run: bun test index.test.ts

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sox python3 python3-pip python3-venv

      - name: Setup Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install faster-whisper

      - name: Generate test audio
        run: sox -n -r 16000 -c 1 -b 16 test-fixtures/test-audio.wav synth 1 sine 440

      - name: Run integration tests
        run: bun test integration.test.ts
